# Be sure to restart your server when you modify this file.
# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dbca39618d2821677085379c219f08e312ebc1fb26987b5045e18a701e335ce034812c5d1b3fc9c6ed14fff48cc5ce6f51ac54f74d039f460f4fbe26a818ff84
  database:
      :host: localhost
      :name: ruby
      :username: ruby_admin
      :password: secret

test:
  secret_key_base: 813df2220bc345db64695318613ac4e8372f2a09459409ff0cc75155c04bc56cc272dd79f13b7e0b7a5afdb74d9c5917152df155f1c68c8f641ee5c0e73a6519
  database:
        :host: localhost
        :name: ruby_test
        :username: ruby_admin
        :password: secret

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
